### ISSUE TITLE
Only seeing a handful of mods in the FMM

### ISSUE THREAD

**Issue by lanes100** [Clef-0/FMM#4]
![image](https://user-images.githubusercontent.com/37626378/39228489-67384da6-4899-11e8-8b9b-9060f8b26b99.png)
This is what i see on the downloads screen. There is no Halo 3 sound packs which I really wanted to get the full Halo 3 experience.

**Comment by quiche-swe** [comment]
I'm having the same problem, except with even less mods (5 only). Hoping to get an answer or fix!

**Comment by Clef-0** [comment]
response to OP: those are the only mods compatible with 0.6 so far.
response to vince: some mods were temporarily removed, there's a copy on the subreddit though that someone posted, I'll restore them soon.
